#!/bin/python3

import tkinter as tk
import tkinter.font
import os
from functools import partial

test_mode = False
#test_mode = True

if test_mode :
    oven_size = 524288
else :
    oven_size = 263748

oven_path = os.path.expanduser ( "~/Casting" )
mcube_path = os.path.expanduser ( "~/MCUBE" )

# We have these "modes"
INIT = 99
TASK = 1
SHM = 2
STARTUP = 3

DEF_WIDTH=300

# "dest" status on ipcs means "marked to be destroyed".
# It actually will be destroyed when all applications that
# have it attached have terminated.

class Cleaner:
    def __init__ (self) :

        self.mw = tk.Tk()
        self.mw.title('Oven Starter / Cleaner')

        os.chdir ( oven_path )

        fixed_font = tkinter.font.nametofont("TkFixedFont")
        self.mw.option_add("*Font", fixed_font)

        root = tk.Frame ( self.mw, width=DEF_WIDTH ).pack ()
        self.root = root

        f1 = tk.Frame ( root, pady=10 )
        f1.pack()

        self.sb = tk.Button( f1, text="Startup", command=self.reload_start)
        self.sb.pack(side='left')

        self.bu = tk.Button( f1, text="Shared Memory", command=self.reload_shm)
        self.bu.pack(side='left')

        self.tsk = tk.Button( f1, text="Tasks", command=self.reload_task)
        self.tsk.pack(side='left')

        self.qu = tk.Button( f1, text="Quit", command=self.mw.destroy)
        self.qu.pack(side='left')

        self.f2 = tk.Frame ( root, width=DEF_WIDTH )
        self.f2.pack()

        self.f3 = tk.Frame ( root )

        self.ma = tk.Button( self.f3, text="Check all", command=self.ckall)
        self.ma.pack(side='left')
        self.ua = tk.Button( self.f3, text="Uncheck all", command=self.unckall)
        self.ua.pack(side='left')

        self.nk = tk.Button( self.f3, text="Nuke 'em", command=self.nuke)
        self.nk.pack(side='right', padx=50 )
        # self.f3.pack()

        self.f4 = tk.Frame ( root )
        v = tk.IntVar()
        v.set(1)
        self.oven = v
        tk.Radiobutton(self.f4, text="Main oven", padx = 20,
            command=self.change_oven,
            variable=v, value=1).pack(side='left')
        tk.Radiobutton(self.f4, text="Meter cube", padx = 20,
            command=self.change_oven,
            variable=v, value=2).pack(side='left')

        # load up the first tab
        self.mode = INIT
        self.info = []
        #self.reload_shm ()
        self.reload_start ()

        tk.mainloop()

    def find_pid ( self, who ) :
        tasks = os.popen('ps -eo pid,command').read().splitlines()
        for ll in tasks[1:] :
            ww = ll.split()
            # Note broken, stupid python "stop" on a slice is one beyond the last item
            xx = ' '.join( ww[1:3] )
            if xx == who :
                return ww[0]
        return None

    def ckall ( self ) :
        for w in self.info :
            (l,c,v) = w
            v.set(1)

    def unckall ( self ) :
        for w in self.info :
            (l,c,v) = w
            v.set(0)

    def unload ( self ) :
        if self.mode == INIT :
            return

        if self.mode == STARTUP :
            for w in self.info :
                w.destroy ()
        else :
            for w in self.info :
                (l,c,v) = w
                #print ( l )
                c.destroy ()
        self.info = []

    # get rid of either a process or a shm segment
    def nuke_one ( self, line ) :
        ww = line.split()
        if self.mode == SHM :
            cmd = "ipcrm -m " + ww[1]
            print ( cmd )
            os.system ( cmd )
        else :
            cmd = "kill -9 " + ww[0]
            #print ( cmd )
            os.system ( cmd )

    # get rid of all selected items
    def nuke ( self ) :
        for w in self.info :
            (l,c,v) = w
            if v.get() == 1 :
                self.nuke_one ( l )
            if self.mode == SHM :
                self.reload_shm ()
            else :
                self.reload_task ()

    def task_pid ( self, line ) :
        ww = line.split()
        pid = int ( ww[2] )

    def reload_stuff ( self, stuff ) :
        self.info = []
        for l in stuff :
            v = tk.IntVar()
            v.set(0)
            c = tk.Checkbutton( self.f2, text=l, variable=v)
            self.info.append ( (l,c,v) )
            c.pack ()

# ----------------------------------
# - stuff for shared memory tab

    def reload_shm ( self ) :
        self.unload ()
        if self.mode == STARTUP :
            self.f3.pack()
            self.f4.pack_forget()
        self.mode = SHM
        self.reload_stuff ( self.get_shm() )

    def get_shm ( self ) :
        # First 3 lines are header stuff
        # Last line is blank
        #ipcs = os.popen('ipcs').readlines()
        ipcs = os.popen('ipcs -m').read().splitlines()
        rv = []
        for ii in ipcs[3:-1] :
            ww = ii.split()
            if int(ww[4]) == oven_size :
                rv.append ( ii )
        return rv

# ----------------------------------
# - stuff for tasks tab

    def reload_task ( self ) :
        self.unload ()
        if self.mode == STARTUP :
            self.f3.pack()
            self.f4.pack_forget()
        self.mode = TASK
        self.reload_stuff ( self.get_tasks() )

    # first line is header
    def get_tasks ( self ) :
        #tasks = os.popen('ps -alx').read().splitlines()
        tasks = os.popen('ps -eo pid,user,bsdtime,command').read().splitlines()
        rv = []
        for ll in tasks[1:] :
            ww = ll.split()
            # print ( ll[:80] )
            keep = False
            if "iraf" in ll :
                keep = True
            if "oven" in ll :
                keep = True
            if "mirror" in ll :
                keep = True
            if test_mode and "xfce" in ll :
                keep = True
            if keep :
                #print ( ww[12] )
                rv.append ( ll[:100].ljust(100) )
        return rv

# ----------------------------------
# - stuff for startup tab

    def reload_start ( self ) :
        self.unload ()
        if self.mode != STARTUP :
            self.f3.pack_forget()
        self.f4.pack()
        self.mode = STARTUP
        self.change_oven ()

    def change_oven ( self ) :
        self.unload ()

        self.info = []
        if self.oven.get() == 1 :
            os.chdir ( oven_path )
            self.st_one ("ovend")
            self.st_one ("ovene -c0")
            self.st_one ("ovene -c1")
            self.st_one ("ovene -c2")
        else :
            os.chdir ( mcube_path )
            self.st_one ("ovend -M")
            self.st_one ("ovene -M")
        self.st_one ("ovenp")
        self.st_one ("ovenb")
        if self.oven.get() == 1 :
            self.sm_one ( "100" )
            self.sm_one ( "101" )
            self.sm_one ( "102" )
        else :
            self.sm_one ( "110" )
        print ( "In directory: " + os.getcwd() )

    def st_one ( self, who ) :
        f = tk.Frame ( self.f2, width=DEF_WIDTH )
        f.pack()
        self.info.append ( f )

        l1 = tk.Label( f, text=who.ljust(10) )
        l1.pack(side='left')

        if self.find_pid ( who ) == None :
            status = "not running"
            color = 'yellow'
        else :
            status = "Running!"
            color = 'green2'

        status = ("  " + status).ljust(24)
        l2 = tk.Label( f, text=status, bg=color )
        f.configure ( bg=color )

        l2.pack(side='left')

        b1 = tk.Button( f, text="Start", command=partial(self.st_start,who))
        b1.pack(side='left')
        b2 = tk.Button( f, text="Stop", command=partial(self.st_stop,who))
        b2.pack(side='left')
        b3 = tk.Button( f, text="Restart", command=partial(self.st_restart,who))
        b3.pack(side='left')

    def st_start ( self, who ) :
        cmd = who + " &"
        os.system ( cmd )
        self.reload_start ()

    def st_stop ( self, who ) :
        pid = self.find_pid ( who )
        if pid != None :
            print ( "Found: " + pid )
            os.system ( "kill -9 " + pid )
        else :
            print ( "Not running" )
        self.reload_start ()

    def st_restart ( self, who ) :
        self.st_stop ( who )
        self.st_start ( who )
        #self.reload_start ()

    def find_shm ( self, who ) :
        return None

    # Set up a line in the Start GUI for a shm segment
    def sm_one ( self, who ) :
        f = tk.Frame ( self.f2, width=DEF_WIDTH )
        f.pack()
        self.info.append ( f )

        lab = "shm " + who
        l1 = tk.Label( f, text=lab.ljust(10) )
        l1.pack(side='left')

        if self.find_shm ( who ) == None :
            status = "none"
            color = 'yellow'
        else :
            status = "OK"
            color = 'green2'

        status = ("  " + status).ljust(24)
        l2 = tk.Label( f, text=status, bg=color )
        f.configure ( bg=color )

        l2.pack(side='left')

        b1 = tk.Button( f, text="Load from oven", command=partial(self.st_start,who))
        b1.pack(side='left')
        b2 = tk.Button( f, text="Load from disk", command=partial(self.st_stop,who))
        b2.pack(side='left')


Cleaner ()

# THE END
