#!/usr/bin/perl

# tjt - renamed to ovenw 1-12-2021
# now "cleaner" will start this automatically
#
# Note that "ovenw" conflicts with a hidden builtin that is part of the
# IRAF oven software.  The IRAF thing does a "wait" rather than a "watch"
# and has nothing to do with errors or blowing the whistle.
# rather IRAF-ovenw is used in scripts like ovenc.cl to synchronize
# actions in the script with oven timings.
#
# This used to be called watch.pl and was written by John Hill
# watch -- watch the oven error log and make a noise when something is added
#
# call as a cgi script
#
# Copyright (C) 2013 by J. M. Hill
# Created at Steward Observatory 
# Argument sets the refresh time in seconds, 20>
# Hacked for linux by Tom Trebisky 7/8/2019
#

$version = "23AUG13";
$version = "08JUL19";

# strip \'s put in by server (apparently)
$ARGV[0] =~ s/\\(.)/$1/g;

# configuration
# $path = "/home/pilot/errors.log";
$path = "./errors.log";
$cmd = "/usr/bin/wc ";

# When we got ready to use this 11-15-2021 we discovered that
# aplay had changed and was no longer willing to play sparc audio files.
# There may be some way to coerce it, but we never figured it out.
# So we installed "sox" and used it to covert the sparc ".au" file to wav.
# Probably "wav" file support won't vanish unexpectedly anytime soon.
#$sound = "/usr/local/bin/train.au";
$sound = "/usr/local/bin/train.wav";

#print "Whistles when something appears in $path \n";

unless (-e $path) {
    print "File: $path doesn't exist.\n";
    exit;
}

# Use wc to check the size of errors.log
@initialmatches = `$cmd $path`;

#print "Size $initialmatches[0] \n";

sub toot {
    # system("cat /usr/demo/SOUND/sounds/train.au > /dev/audio");
    system ( "aplay -q $sound" );
}

toot ();

# Loop forever until a ^C
while ( 1 > 0 ) {
	sleep(30); # wait 30 seconds
	@matches = `$cmd $path`;
	#print "Size $matches[0] \n";
	if ($matches[0] > $initialmatches[0]) { 
		toot ();
		sleep(1);
		toot ();
		$initialmatches[0] = $matches[0];
	} # end if
} # end infinite while
