# Build all these little pieces
# Delete the template files that we no longer need.

all:
	../makemenus ../menus/*
	rm -f *.tc

# These are "templates" and we never use them,
#  so they might as well get cleaned out

tc_clean:
	rm -f *.tc

clean:
	rm -f *.tc
	rm -f ../menusm/menus.vc
	rm -f ../menusm/menus.ext
